### ISSUE TITLE
Player randomly freezing between midnight and 4:30 AM

### ISSUE THREAD

**Issue by atenfyr** [atenfyr/bettertaxes#9]
On certain machines, after midnight of any given day, there is a chance that one or more of the players online will be frozen and unable to move (implying an infinite loop in the player code) until 4:30 AM (which is the deadline for tax auto-collection).

I suspect that this is a direct result of either a flaw in the auto-collection code, a flaw in the gate parser, or a mod conflict.

**Comment by cheeeeeeeeeen** [comment]
More information about this issue:

It seems to be bound on the Player. Once it happens, every world the player enters (with the same mods that will be listed after and same time: midnight to dawn) they will be frozen. I don't know the cause, but it did happen the first night the moment the tax collector found a home.

Mods:
```json
[
"AccessorySlotsPlus",
"AutoTrash",
"BannerBonanza",
"BetterBuffs",
"BetterTaxes",
"Bluemagic",
"BossCursor",
"CalamityMod",
"CalamityModMusic",
"ChensCursedAccessories",
"ChensGradiusMod",
"ClamExtraMusic",
"HelpfulHotkeys",
"HEROsMod",
"ItemControl",
"Loot",
"MorePotions",
"NPCControl",
"Pumpking",
"RecipeBrowser",
"SummonersAssociation",
"ThoriumMod",
"WheresMyItems",
"WingSlot",
"MaxStackPlus",
"ChensForcedTeamworkMod",
"BossChecklist"
]
```

Some of my mods here are not in mod Browser due to the recent Mod Browser crash. I will re-upload them.

**Comment by atenfyr** [comment]
Even though it's been a while, I'm fairly certain that this latest patch (Better Taxes 2.3.2) has introduced a change which should fix this seemingly multiplayer-specific bug. If you've got the time, can you test out this new update and see if it resolves the issue?
